# -*- coding: utf-8 -*-
"""project ml nlp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14rREnZH9LmD-Dsis99XR72XJU_zM7Dm7
"""

import pandas as pd
import re
import string
import joblib

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

df = pd.read_csv("spam_data.csv", encoding="latin-1")

df = df[['v1', 'v2']]
df.columns = ['label', 'text']

df['label'] = df['label'].map({'ham': 0, 'spam': 1})
print(df.head())

def clean_text(text):
    text = text.lower()
    text = re.sub(r'\d+', '', text)
    text = re.sub(r'\[.*?\]', '', text)
    text = re.sub(r'https?://\S+|www\.\S+', '', text)
    text = re.sub(r'<.*?>+', '', text)
    text = re.sub(r'[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub(r'\n', '', text)
    return text

df['text'] = df['text'].apply(clean_text)

X = df['text']
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = Pipeline([
    ("tfidf", TfidfVectorizer(
        stop_words='english',
        max_features=5000
    )),
    ("clf", LogisticRegression(max_iter=1000))
])

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

save_path = r"C:\Users\dhara\OneDrive\Documents\DCK\news project\spam_nlp_model.pkl"

joblib.dump(model, "spam_nlp_model.pkl")

print("✅ Model saved as spam_nlp_model.pkl")